### ISSUE TITLE
Setup browser based test harness

### ISSUE THREAD

**Issue by ross-weir** [ross-weir/ergode#55]
Most dev is going to be done using native CLI as it's faster & easier. Same with unit tests.

It will be important to get browser tests running ASAP to ensure web platforms continue to work

Ideas:

1. Create a subproject that uses the npm package produced by `deno task build:npm`
2. Subproject runs the node in a web browser using something like `puppeteer` or `wdio`
3. Probe the web node at intervals, etc to make sure it's reaching the desired state
    - To begin with maybe just connect to testnet and get to `n` connected peers
    - In future maybe run a local devnet and do more in-depth tests
4.  Create a websocket bridge using deno for use in browser integration tests

Run it every 4 hours or so? Or on PRs? Maybe do on PRs to begin with then when the tests start taking over 10 minutes move to a schedule.

Maybe has inspiration, they have browser based tests: https://github.com/libp2p/js-libp2p

---

Solution started in #58 , remaining:

- [x] ~~create `deno` based websocket bridge so its easy to run in project~~ completed in #60 
- [x] ~~add puppeteer to `e2e-web` project to launch node in a real browser and track state outputted as JSON to element with `id=node-state`~~ done in #61 
- [x] ~~ensure 3 peers are connected after 2 minutes (as a start)~~ done in #61 
- [x] ~~Make script that launches ws bridge then runs puppeteer tests~~ done in #62 
- [x] Add e2e tests to CI/CD - is this level of TCP connections allowed in GH actions?
- [x] ~~attempt to use `scorex-buffer` ESM instead of importing browser bundle~~ the deno CDNs seem to have an issue with WASM files, not a big deal, keep using browser bundle

**Comment by ross-weir** [comment]
To begin with something semi-manual that can be ran locally will be at least something. Can work on a more robust/fully automated/CICD solution later as it might be tricky.

Start with:
- NPM based subproject that installs the node as a dependency
- `mocha` in the browser: https://mochajs.org/#running-mocha-in-the-browser
- Create a websocket bridge
- Have a script that starts bridge, bundles the subproject, then opens a html file like in the `mocha` link in the default browser and imports the bundle
- Watch the output to make sure it all looks good
- Could create long running test cases using mocha with a timeout

**Comment by ross-weir** [comment]
- [ ] create `deno` based websocket bridge so its easy to run in project
- [ ] add puppeteer to `e2e-web` project to launch node in a browser and track state outputted as JSON to element with `id=node-state`
- [ ] ensure 3 peers are connected after 2 minutes (as a start)
